image: docker:latest

services:
  - docker:dind

stages:
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apk update
  - apk add npm yarn python g++ make util-linux
  - yarn install

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - /v\d*\.\d*\.\d*/
  except:
    - branches
  script:
    # build the package
    - npm run build
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
