image: ubuntu:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  artifacts:
    untracked: true
  only:
    - /v\d*\.\d*\.\d*/
  except:
    - branches
  script:
    - apt-get update
    - apt-get -y install npm yarn python g++ make util-linux
    - yarn install
    # build the package
    - npm run build

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - /v\d*\.\d*\.\d*/
  except:
    - branches
  dependencies:
    - build
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
